paths:
  uploads: static/img
  static: static
collections_config:
  pages:
    path: content
    icon: wysiwyg
    url: "/{slug}/"
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
  blog:
    path: content/blog
    icon: article
    url: "/blog/{slug}/"
    glob:
      - '!_index.md'
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
  includes:
    path: content/includes
    glob:
      - '!_index.md'
    icon: circles
    disable_url: true
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
