paths:
  uploads: static/img
  static: static
collections_config:
  pages:
    path: content
    icon: wysiwyg
    url: "/{slug}/"
    glob:
      - '!blog/*'
      - '!includes/*'
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    _inputs:
      title:
        type: text
        label: Page Title
        options:
          required: true
      slug:
        type: text
        label: URL Slug
        comment: The URL of the post, e.g. /<slug here>
        options:
          required: true
      draft:
        type: switch
        label: Draft
        comment: Drafts appear in previews but not the main site.
    schemas:
      page:
        path: schemas/page.md
        name: Page
        icon: post_add
  blog:
    path: content/blog
    icon: article
    url: "/blog/{slug}/"
    glob:
      - '!_index.md'
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    create:
      extra_data:
        filename: '{date|year}-{date|month}-{date|day}-{slug}'
      path: '[relative_base_path]/{filename|slugify}.[ext]'
    _inputs:
      title:
        type: text
        label: Blog Title
        options:
          required: true
      slug:
        type: text
        label: URL Slug
        comment: The URL of the post, e.g. /blog/<slug here>
        options:
          required: true
      date:
        type: date
        label: Publish date
        instance_value: NOW
        disable_instance_value_rehydration: true
        comment: Posts with dates in the future will not be visible.
        options:
          required: true
      draft:
        type: switch
        label: Draft
        comment: Drafts appear in previews but not the main site.
    schemas:
      blog:
        path: schemas/blog.md
        name: Blog Post
        icon: post_add
  includes:
    path: content/includes
    glob:
      - '!_index.md'
    icon: circles
    disable_url: true
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
