baseURL = 'https://spinel.coop'
locale = 'en-us'
title = 'Spinel, the Ruby open source maintainers‘ co-op'
summaryLength = 20

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']

[services.rss]
limit = 50

# allow html inside markdown files
[markup.goldmark]
renderer.unsafe = true

# remove tags and categories
disableKinds = ["taxonomy", "term"]
[taxonomies]
